### ISSUE TITLE
quiverplot:ish

### ISSUE THREAD

**Issue by zahachtah** [queryverse/VegaLite.jl#130]
Hi, just wanted to see if anyone can advise me on how to do something similar to an quiver plot. The following code works to show where I am going but I want to only have a point marker at the origin (p=1) and a line showing the direction, i.e. I don't need an arrow head. Also, I only was able to make X number of line segments by using the color={field=:id} tag but thats a bit of a hack, any other better solution would be great.

code as follows: 

```julia
N=20
XX=zeros(2*N*N)
YY=zeros(2*N*N)
ID=zeros(Int,2*N*N)
P=zeros(Int,2*N*N)
for i in 1:N
    for j in 1:N
        k=(i-1)*2*N+(j-1)*2+1
        XX[k]=i
        XX[k+1]=Float64(i)+(rand().-0.5)
        YY[k]=j
        YY[k+1]=Float64(j)+(rand().-0.5)
        ID[k]=k
        ID[k+1]=k
        P[k]=1
        P[k+1]=0
    end
end

D=DataFrame(x=XX,y=YY, id=ID, p=P)

D |>@vlplot(background=:white,legend=false, width=600,height=400) +
@vlplot(
    :line,
    x=:x,
    y=:y,
    color={field=:id, color=:black, legend=false},
    background=:white
) +
@vlplot(
    width=600,
    height=400,
    :point,
    x=:x,
    y=:y,
    color={field=:p, scheme=[:black, :white],legend=false},
    background=:white
)
```

**Comment by davidanthoff** [comment]
Maybe this looks even better:
````julia
D2 |>@vlplot(background=:white,width=600,height=400, color={value=:black}) +
    @vlplot(:rule, x=:x, y=:y, x2=:x2, y2=:y2) +
    @vlplot(:circle, x=:x, y=:y)
````
Gives me:
![visualization 4](https://user-images.githubusercontent.com/1036561/48800991-1da48f80-ecc0-11e8-8cf9-fce01d8ce584.png)

**Comment by zahachtah** [comment]
That was perfect. didn't know about the :rule and how to arrange the data. neat!

thanks

**Comment by davidanthoff** [comment]
I think with the new `angle` encoding channel this should now be much easier: use a `point` mark with shape `arrow`, and then just slightly modify [this](https://www.queryverse.org/VegaLite.jl/v2.1/examples/examples_table_based_plots/#Wind-Vector-Map-1) example.
