### ISSUE TITLE
Document REPL and display mechanism

### ISSUE THREAD

**Issue by PetrKryslUCSD** [queryverse/VegaLite.jl#132]
I am running
```
using VegaLite
using DataFrames

d = Normal()
x = rand(d, 1000)
y = rand(d, 1000)
df  = DataFrame(x=x, y=y) 
df |> 
@vlplot(
    :point,
    x=:x,
    y=:y,
    width=400,
    height=400
)
```
in a script. No plot is produced. I only will get a plot if I select
```
df |> 
@vlplot(
    :point,
    x=:x,
    y=:y,
    width=400,
    height=400
)
```
and paste it into the repl command line. Is this the expected behavior? If so, how do I get a plot from within a script? Thanks.

**Comment by PetrKryslUCSD** [comment]
I think I figured out that this was intentional. I think it wants me to chain it with `display`:
```
df |> 
@vlplot(
    :point,
    x=:x,
    y=:y,
    width=400,
    height=400
) |> display
```

**Comment by davidanthoff** [comment]
Yes, that is the standard julia multimedia display story here: ``@vlplot`` returns an instance that can be displayed. If you are at the REPL, and an expression returns it, it will automatically be displayed (in the same way if you type ``x = 5`` in the REPL, it will show ``5`` on the next line). In a script, return values are not automatically displayed, instead you need to call ``display`` on them.

We should add some text to the documentation about this, though.

**Comment by jlewis91** [comment]
@davidanthoff think this maybe can be closed?
