### ISSUE TITLE
Shorthand does not work for plot with facets and layers

### ISSUE THREAD

**Issue by aterenin** [queryverse/VegaLite.jl#135]
In a plot which includes both facets and layers, `x1:q` and similar shorthand does not work. In particular if we replace `x = { field = :x1, type = :quantitative },` in the below with `x = "x1:q"` results in an invalid spec error. Replacing it with `x = { "x1:q" }` results in nothing showing up.

```
  @vlplot(
    facet = { column = { field = :type, type = :nominal } },
    spec = {
      layer = [{
        mark = :rule, height=1000, width=100, encoding = {
          x = { field = :x1, type = :quantitative },
          x2 = { field = :x2, type = :quantitative },
          y = { field = :y1, type = :quantitative },
          y2 = { field = :y2, type = :quantitative },
          color = { field = :type, type = :nominal }
        }
      },{
        mark = :rule, height=1000, width=100, encoding = {
          x = { field = :x2, type = :quantitative },
          x2 = { field = :x3, type = :quantitative },
          y = { field = :y2, type = :quantitative },
          y2 = { field = :y3, type = :quantitative },
          color = { field = :type, type = :nominal }
        }
      },{
        mark = :rule, height=1000, width=100, encoding = {
          x = { field = :x1, type = :quantitative },
          x2 = { field = :x3, type = :quantitative },
          y = { field = :y1, type = :quantitative },
          y2 = { field = :y3, type = :quantitative },
          color = { field = :type, type = :nominal }
        }
      }]
    }
  )
```

**Comment by davidanthoff** [comment]
Thanks!

There is also another way to create this plot, that I haven't found time to document yet... But here is how (I think) it would look (I left out some properties, but you'll get the idea):
````julia
data |> @vlplot(
    facet = { column = { field = :type, type = :nominal } }
) + (
  @vlplot(:rule, x="x1:q", x2="x2:q", y="y1:q", y2="y2:q", color="type:n") +
  @vlplot(:rule, x="x2:q", x2="x3:q", y="y2:q", y2="y3:q", color="type:n") +
  @vlplot(:rule, x="x1:q", x2="x3:q", y="y1:q", y2="y3:q", color="type:n") +
)
````
The story is roughly this:
1. When you add two specs with ``+``, and the spec on the left side has a ``facet`` element, then the spec on the right hand side will become the "sub-spec", i.e. will become the content of the ``spec`` JSON element.
2. If you add specs with ``+`` like in the parenthesis, they will become all layered.

I haven't tried the code above because I don't have the data, but roughly that is the idea.

Feedback on that would be welcome, and I obviously should just write a section in the docs about this :)

**Comment by davidanthoff** [comment]
Oh, and I'm leaving this open as a bug as well, because your example should of course also work, that is a plain old bug.

**Comment by aterenin** [comment]
Thanks very much for that example - with some tiny modifications, it works and is much cleaner!

```
@vlplot(
    facet = { column = { field = :type, type = :nominal } }
  ) + (
    @vlplot(height=1000, width=100) +
    @vlplot(:rule, x="x1:q", x2="x2:q", y="y1:q", y2="y2:q", color="type:n") +
    @vlplot(:rule, x="x2:q", x2="x3:q", y="y2:q", y2="y3:q", color="type:n") +
    @vlplot(:rule, x="x1:q", x2="x3:q", y="y1:q", y2="y3:q", color="type:n")
  )
```

The `@vlplot(height=1000, width=100)` (or, if not setting height/width, `@vlplot()`) needs to be separate otherwise some (but not all) data points get dropped from the first layer (VegaLite bug?). This code yields more or less the same VLSpec as the original code.

The parentheses around the last three @vlplot commands are critical, otherwise the facets don't show up - this was what prevented me from getting faceting to work by just following the documentation.

It would be nice to be able to write `facet = { column = "type:n" }` instead of as above.

Partial data set for the above plot given below.

```
x1,x2,x3,y1,y2,y3,type
1.0,2.0,1.5,30.0,30.0,29.4,1.0
2.0,3.0,2.1,30.0,30.0,29.1,1.0
1.0,0.0,0.9,30.0,30.0,29.1,1.0
1.0,1.5,0.9,30.0,29.4,29.1,1.0
2.0,1.5,2.1,30.0,29.4,29.1,1.0
3.0,2.1,3.0,30.0,29.1,29.0,1.0
0.0,0.9,0.0,30.0,29.1,29.0,1.0
1.5,0.9,1.5,29.4,29.1,28.5,1.0
1.5,2.1,1.5,29.4,29.1,28.5,1.0
2.1,3.0,2.3,29.1,29.0,28.4,1.0
1.5,1.5,0.9,15.5,14.1,14.8,2.0
1.5,2.1,1.5,14.1,13.4,12.8,2.0
1.5,0.9,0.9,14.1,14.8,13.4,2.0
2.1,1.5,2.1,13.4,12.8,12.1,2.0
1.5,1.5,0.9,14.1,12.8,13.4,2.0
1.5,2.1,1.5,12.8,12.1,11.4,2.0
1.5,0.9,0.9,12.8,13.4,12.1,2.0
2.1,1.5,2.1,12.1,11.4,10.7,2.0
1.5,1.5,0.9,12.8,11.4,12.1,2.0
1.5,2.1,1.5,11.4,10.7,10.0,2.0
1.5,0.9,0.9,11.4,12.1,10.7,2.0
```
