### ISSUE TITLE
short code for boxplot

### ISSUE THREAD

**Issue by sdewaele** [queryverse/VegaLite.jl#148]
Is is possible to use the shorter form for creating a boxplot as described [here](https://vega.github.io/vega-lite/docs/boxplot.html) in the vega-lite docs, instead of the [longer version](http://fredo-dedup.github.io/VegaLite.jl/latest/examples/examples_box_plots/) in the VegaLite.jl documentation? I have tried but could not get it to work. Here is my attempt:

```
df |> @vlplot(
  mark={
    typ="boxplot",
    extent="min-max"
  },
  encoding={
    y = "predictor:n",
    x="samplevalue:q"
  }
)
```

**Comment by davidanthoff** [comment]
Not yet. The box plot is a new feature in vega-lite 3.0, and they have not yet released a final version of it. VegaLite.jl always tracks the latest released version of vega-lite, which currently is 2.6.0. Once the have a final vega-lite 3.0 release out, we'll update here and then it should just work.

Maybe I should create a branch here to try out the vega-lite 3.0 release candidates, if I find some time I might do that, and then you could use that in the meantime.

**Comment by sdewaele** [comment]
Thanks! I am okay to wait until the release is out; the longer version also works for me for now. I was wondering if I just made an error in my code and that was the reason it did not work.

**Comment by davidanthoff** [comment]
I wish the vega-lite documentation didn't track their pre-release versions, but instead the released versions, that has tripped me many times also, that I tried something that I saw on their end, only to then see that it hasn't been released...

**Comment by davidanthoff** [comment]
I think this should work now, the shipping version of VegaLite.jl is now based on vega-lite 3.
