### ISSUE TITLE
Figure out whether we can drop Cairo.jl

### ISSUE THREAD

**Issue by davidanthoff** [queryverse/VegaLite.jl#158]
Maybe https://github.com/vega/vega/pull/1517 can help. First step is to figure out what dependencies that has and whether we can use that instead of Cairo.jl to generate png, pdf etc.

**Comment by tkf** [comment]
FYI I've been using a monkey patch

```julia
for (MIMEType, format) in [
    (MIME"application/pdf", "pdf"),
    (MIME"application/eps", "eps"),
    (MIME"image/png", "png"),
],
    VGType in [VegaLite.VGSpec, VegaLite.VLSpec{:plot}]

    @eval function Base.show(io::IO, ::$MIMEType, v::$VGType)
        buf = IOBuffer()
        format = $format
        proc = open(`rsvg-convert --format $format`, "r+")
        @async begin
            show(proc.in, "image/svg+xml", v)
            close(proc.in)
        end
        write(io, proc.out)
        success(proc)
        return
    end
end
```

to use `rsvg-convert` CLI and instead of Cairo.jl and Rsvg.jl.  Maybe it's OK to rely on a CLI since VegaLite.jl already invokes Node.js as a subprocess?  I think you can directly pipe node output to rsvg-convert to increase the performance somewhat.

**Comment by davidanthoff** [comment]
Yes, I think relying on a process would be fine! So the question then becomes: can we get reliable binary downloads for `rsvg-convert` on all platforms? I briefly googled around, and nothing jumped at me, but maybe I just didn't look careful enough?

I think right now Cairo.jl should be working on all platforms. Or are you having issues currently? I still have hope that someone will create a BinaryBuilder.jl for Cairo/Rsvg/Gtk, so that we can stick with them but just solve the deployment problems...

**Comment by tkf** [comment]
> I think right now Cairo.jl should be working on all platforms. Or are you having issues currently?

I just did the monkeypatch as a quick workaround for https://github.com/lobingera/Rsvg.jl/issues/26 and kept using it.  I don't think I need this now.

> can we get reliable binary downloads for `rsvg-convert` on all platforms?

Ah, I missed this point.  No, I don't know if there is a pre-build binary for all OSes.  I find https://packages.debian.org/sid/amd64/librsvg2-bin/filelist for Debian.  Considering Rsvg.jl managed to cover macOS and Windows as well, maybe you can get it from Homebrew and WinRPM as well?  But I guess it does not improve the situation if we need to set up BinDeps (or BinaryBuilder) for `rsvg-convert`...

**Comment by davidanthoff** [comment]
I think I figured out how we can use https://github.com/Automattic/node-canvas, which might be more stable. PR coming soon.
