### ISSUE TITLE
Transfer repo to queryverse organization?

### ISSUE THREAD

**Issue by davidanthoff** [queryverse/VegaLite.jl#166]
@fredo-dedup do you think it would make sense to transfer this repo over to https://github.com/queryverse? It would make it easier for me to maintain things, and I think it might also expose the package to more potential users. Of course you would maintain complete admin rights with the repo! No problem if you were to prefer to just keep it here.

Also, hope you are ok? Do you think you will at some point come back to this package?

**Comment by fredo-dedup** [comment]
Hi David,
I have no issue with this transfer especially if it makes things easier for you. I have had a few ideas for some time but nothing concrete, and barely the time to work on them ! So realistically I don't think I will make contributions in the near future.
And again, thanks for all the care you have put into this package !

**Comment by davidanthoff** [comment]
Fantastic! I think you need to initiate the transfer in settings, could you do that? And then I can accept the transfer on the queryverse end of things.

**Comment by fredo-dedup** [comment]
I initiated the transfer to 'queryverse'

**Comment by davidanthoff** [comment]
Hm, so far I'm not getting any notification... You just did the transfer repository thing in the settings, right?

**Comment by fredo-dedup** [comment]
I did it again and it says that I don't have the rights to create a repo on queryverse. Should I have some permissions there to do the transfer ?

**Comment by davidanthoff** [comment]
I just made you a co-owner of queryverse, hopefully that will allow the transfer. Once it is done, I'll revert you back to a normal member :)

**Comment by fredo-dedup** [comment]
It seems to work now. Do you have the notification ?

**Comment by davidanthoff** [comment]
Yeah, it is here, so all good :) I'll remove you as an owner from queryverse, but will add you with full rights to this repo!
