### ISSUE TITLE
API to manipulate Vega Lite properties directly?

### ISSUE THREAD

**Issue by tkf** [queryverse/VegaLite.jl#168]
Is there a public interface to mutate Vega Lite properties?  For example, to change/add plot title, I know I can do

```julia
plt = @vlplot(...)
plt.params["title"] = "Title"
```

but it feels wrong since I'm guessing `.params` is an implementation detail.

If there are no easy way to change Vega Lite properties already, how about overloading `getproperty` and `setproperty!` so that you can simply modify properties?

```julia
plt.title = "Title"
```

One drawback in this approach is that there is no easy way to easily unset property.  But maybe setting `nothing` to clear out a field like

```julia
plt.config = nothing
```

is OK?

**Comment by davidanthoff** [comment]
For a while I had thought of plots as unmutable things, but right now I can’t think of a good reason why. And I very much see the point and elegance of what you suggest... So right now nothing like that exists, but maybe we could add it as an experimental feature and see how it goes?

Generally it might be nice to have an API that allows for a more incremental construction of specs. We had something like that in the past that was functional (in the sense of non-mutable) in the past, but maybe a mutable API could play a similar role.

So, short summary: this strikes me very much worth experimenting but at the same time I think we should hold off a bit before we commit to something for good.

**Comment by tkf** [comment]
Hi, thanks for the positive response (and sorry for the delay in reply).

I'm all for immutable/functional API.  The reason why I proposed the mutable API was because it was simple to propose (and I didn't know how much people like immutable API).

I think a big advantage for implementing immutable API would be that you can treat the Vega spec as a persistent data structure.  In particular, it's easy to construct slightly different plots viewing the same table without `deepcopy`'ing the spec (and hence the table).  It lets you go back to the original plot after you created slight variants of it and be confident that the original plot is not modified.  (`deepcopy` probably is not the worst approach ATM since Vega cannot handle big tables anyway as they would be converted into row-oriented format and serialized as JSON.  But I'm hoping that something like https://github.com/vega/vega-loader-arrow would change that.)

If you want to go to immutable API route, I'd recommend using `Lens` interface in [Setfield.jl](https://github.com/jw3126/Setfield.jl).  It lets you create nestable getters and setters for immutable objects.

Having said that, I think starting with mutable API (based on `setproperty!`) would not be so bad.  I don't think it's so hard to add immutable API later and (optionally) deprecate `setproperty!`.

**Comment by tkf** [comment]
I thought about how to do this.  It'd be nice if you can set nested properties directly like this:

```julia
plt = @vlplot(...)
plt.config.axis.grid = true
```

However, in the mutable route based on `getproperty`/`setproperty!`, I think this is actually somewhat hard to implement.  This is because `getproperty` would always need to (e.g.) mutate the parent object just in case the `setproperty!` of sub-object returning it is called.  It is possible to always return a proxy object that only sets things when `setproperty!` is called but I wouldn't say this is straightforward to implement.

Instead, I think it would be much better to use API based on `Setfield.@set`.  It would look like something like this:

```julia
plt = @vlplot(...)
plt = @set plt.config.axis.grid = true
# or equivalently
@set! plt.config.axis.grid = true
```

This would work because the setter method can look at the nested property access "at once".  That is to say, `@set` macro is lowered to the call `set(plt, compose(PropertyLens{:config}(), PropertyLens{:axis}(), PropertyLens{:grid}()), true)`.

I can make a RP if you are OK with adding Setfield as a dependency.
