### ISSUE TITLE
No access to local files

### ISSUE THREAD

**Issue by davidanthoff** [queryverse/VegaLite.jl#170]
With the switch to the `min.js` versions of vega and vega-lite we seem to have lost the ability to access local files. As far as I can tell the `min.js` versions of the code are hard wired to not support local file system access for e.g. data sources. If that is the case, we need to go back to downloading the packages via npm so that we get the server side versions of everything.

@domoritz, is my analysis here correct? I recently tried to change how we ship vega and vega-lite. I now just copy the `min.j` versions of the files into the julia package (see [here](https://github.com/queryverse/VegaLite.jl/tree/master/assets/vega)). And then we run [this](https://github.com/queryverse/VegaLite.jl/blob/master/src/rendering/compilesvg.js) script in node. Am I right that with that setup, vega-loader will never have access to the local file system, because local file system support is just not part of the `min.js` versions of the code?

Just shipping the `min.js` versions has some major benefits in reducing the complexity of the setup step of the julia package, so that is why I tried that approach.

**Comment by domoritz** [comment]
Vega-Lite never reads the data so I don't think there is any problem. Vega's minified file might be optimized for browsers. If you are using Vega on the server, I recommend using the non-minfied, non-bundled version. The bundle is already optimized for browsers (that's what bundling is for).
