### ISSUE TITLE
No plots rendered in browser or notebook

### ISSUE THREAD

**Issue by pdimens** [queryverse/VegaLite.jl#176]
Hello, 

I've been trying to play around with VegaLite to get a feel for it, however, whether I plot as the tutorials instruct or make two simple arrays and plot those as x an y, the code runs without outputting any errors, however there are not plots displayed in either my browsers (Firefox or Brave), and nothing appears within an nteract cell.

Here is the source produced for the browser:
```
<html>
  <head>
    <title>VegaLite plot</title>
    <meta charset="UTF-8">
    <script src="file:///home/pdimens/.julia/packages/VegaLite/5UYyY/deps/lib/vega.min.js"></script>
    <script src="file:///home/pdimens/.julia/packages/VegaLite/5UYyY/deps/lib/vega-lite.min.js"></script>
    <script src="file:///home/pdimens/.julia/packages/VegaLite/5UYyY/deps/lib/vega-embed.min.js"></script>
  </head>
  <body>
    <div id="vgfgo"></div>
  </body>

  <style media="screen">
    .vega-actions a {
      margin-right: 10px;
      font-family: sans-serif;
      font-size: x-small;
      font-style: italic;
    }
  </style>

  <script type="text/javascript">

    var opt = {
      mode: "vega-lite",
      renderer: "svg",
      actions: true
    }

    var spec = {"encoding":{"x":[1,2,3,4,5],"y":[5,4,3,2,1]}}

    vegaEmbed('#vgfgo', spec, opt);

  </script>

</html>
```

I am using a 64bit Archlinux system (Manjaro) with an AMD Ryzen5 processor, if that matters at all for what might be causing this error.
I have attempted to remove the VegaLite and Cairo packages (via the package manager and manually) and rebuild them, but the outcome remains the same.

**Comment by davidanthoff** [comment]
That is not a valid vega-lite spec you are trying to show there. Can you post the julia code that you are using?

**Comment by pdimens** [comment]
```julia
using VegaLite

x = [1,2,3,4,5] ; y = [5,4,3,2,1]
@vlplot(x=x,y=y) |> display
```

**Comment by davidanthoff** [comment]
The first example doesn't work because you can't pass vectors directly to the `@vlplot` macro, you need to pass a tabular data source.

The second example doesn't work because you don't have any mark type there (also true for the first example, actually).

So, the first example needs to be written as:
```julia
using VegaLite, DataFrames

x = [1,2,3,4,5] ; y = [5,4,3,2,1]
DataFrame(x=x, y=y) |> @vlplot(:point, x=:x,y=:y) |> display
```
The second one as:
```julia

data |> @vlplot(:point, x= :Miles_per_Gallon, y= :Acceleration) |> display
```
I think all the examples from the documentation have this the right way, if you found examples that were like what you tried in the docs, please let me know where that is so that I can fix them.

**Comment by pdimens** [comment]
Ah, thanks for the help!

This seems to work in the REPL, but not in nteract, which still produces empty cells:

![image](https://user-images.githubusercontent.com/19176506/59554929-73000100-8f70-11e9-9635-43596df612bf.png)

**Comment by davidanthoff** [comment]
nteract's vega and vega-lite is currently broke, see [here](https://github.com/nteract/nteract/issues/4411). Jupyter notebook and Jupyterlab should work, though.

**Comment by pdimens** [comment]
Understood, thanks!
