### ISSUE TITLE
Errorbars are plotted diagonally with binned variable

### ISSUE THREAD

**Issue by yanivabir** [queryverse/VegaLite.jl#180]
I'm trying to use the :errorbar mark on variable y, with a binned variable x.

`
dat |>  
@vlplot(x = {"x:o", bin = {maxbins = 10}}) +
@vlplot(mark = {:errorbar, extent = :stderr}, 
        y = {"y:q"}) + 
@vlplot(:point, y = "mean(y)")
`

I get the following warnings:
`
WARN Missing type for channel "tooltip", using "nominal" instead.
WARN Channel tooltip should not be used with "binned" bin
`

And a weird looking plot, with the error bars plotted at a 30 degree angle.

Without binning, it works.

**Comment by davidanthoff** [comment]
Are you able to create the plot properly in pure vega-lite JSON in their online editor?

**Comment by davidanthoff** [comment]
I'm going to close this for now because we would really need a more replicable example to do anything on this. @yanivabir if you have more info on this, please feel free to reopen the issue!
