### ISSUE TITLE
saving plots as interactive html?

### ISSUE THREAD

**Issue by josephmarturano** [queryverse/VegaLite.jl#184]
Thank you for implementing a Julia wrapper to Vega-Lite. As a previous Python-Altair user, I found that sharing an interactive .html file with my non-technical colleagues was an effective way to communicate complex data. For example, I would use Altair to generate an html file with a panel of scatterplots and a dropdown menu to permit easy filtering.

Currently, I know that I can still use Altair to save an html file in Julia via PyCall, e.g.:
```
using PyCall
const pd = pyimport("pandas")
const alt = pyimport("altair")

df = pd.DataFrame(Dict("firstcol" => [1,2,3], "secondcol" => [4,5,6]))
altplot = alt.Chart(df).mark_circle(size=50).encode(x="firstcol",y="secondcol", tooltip=["secondcol"]).interactive();
altplot.save("altairgeneratedplot.html")
```

But I could not figure out how to save as html using VegaLite.jl. For example, the following code errors on the last line with "ArgumentError: Unknown file type":
```
using VegaLite, DataFrames
df = DataFrame(firstcol = [1,2,3], secondcol = [4,5,6])
vlplot = df |> @vlplot(mark = {:circle, size=50}, x=:firstcol, y=:secondcol, tooltip=:secondcol)
VegaLite.savefig("vlgeneratedplot.svg", vlplot)
VegaLite.savefig("vlgeneratedplot.html", vlplot)
```

I read #104 from last year and at the time the proposed solution was to save the VegaLite specification and then manually copy the specification into a VegaLite html structure. For me that is too onerous for more than a few plots, particularly given the availability of PyCall. I saw there were some write to html functions at [VegaLite.jl/render.jl](https://github.com/queryverse/VegaLite.jl/blob/master/src/rendering/render.jl), but I did not understand what to use for the "IO" argument. Is that what I should be using to save VegaLite.jl plots as html? If so, could someone provide a simple example?

Thank you for your time.

**Comment by davidanthoff** [comment]
I think that would be a great feature!

I believe the way to add this would be to 1) add support for the HTML MIME type [here](https://github.com/JuliaIO/FileIO.jl/blob/master/src/mimesave.jl) and 2) add a `show` method for the HTML MIME type [here](https://github.com/queryverse/VegaLite.jl/blob/master/src/rendering/show.jl).

We would have to think a bit how we ship the vega and vega-lite code... I guess one option would be that the generated HTML loads it from the web, but then it only works when you are online. Or maybe we could embed the code in the HTML somehow... But that seems more like a detail, we should first get this to work in general.
