### ISSUE TITLE
Wrapped facet example not working

### ISSUE THREAD

**Issue by tkf** [queryverse/VegaLite.jl#192]
Copying example from https://vega.github.io/vega-lite/docs/facet.html#facet-full does not work:

```julia
using VegaLite, VegaDatasets

dataset("barley") |> vl"""
{
  "name": "trellis_barley",
  "mark": "point",
  "height": {"step": 12},
  "encoding": {
    "facet": {
      "field": "site",
      "type": "ordinal",
      "columns": 2,
      "sort": {"op": "median", "field": "yield"}
    },
    "x": {
      "aggregate": "median",
      "field": "yield",
      "type": "quantitative",
      "scale": {"zero": false}
    },
    "y": {
      "field": "variety",
      "type": "ordinal",
      "sort": "-x"
    },
    "color": {"field": "year", "type": "nominal"}
  }
}
"""
```

which creates

![image](https://user-images.githubusercontent.com/29282/66528558-2b6c2a80-eab5-11e9-80bc-cf9744662dba.png)

I'm using VegaLite 37614d1aae0bf6fe8d49caea55ab766127510a31 with the default browser-based display. Strangely, [`Open in Vega Editor` works](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEB2CGC2BTSAuKAXATogNjglgM4D6ARrJjogJ6QA04UAFovgOZPqpjCSHqIADtwCMAJgC+DCJETQAxgHsAJvmhtuoCDIAemxtqgAzfLmXdI1UznPTDUWGzbY2sARaSrY0ege2R0akFkNEgARwBXb3R8dDd8ADdkO0M+eVgqTUgAL0RMRW4jDMJECT8pP0glHEVMLJMzC2pECnoMIJCoaEV4NQzICtSi+UQuNC17PlqxnkgGmybrWyhFYVDPfG8BlP9581DCWOS-GUDgi1rVOBxfeyhqiPhoQm4xcp3LLMJpiwBaPToxiWFgSFFMgTaAQ6F0wV36ZQggygyjcsH0qVBOAiiBeaAA2iceISZKDMODaKEALLeeRMCJktE7VLNVpoEQATgAzCImf4rI00GIAOy8mSHdyhACq0ESeXF1DAADEKPBIISkYYJndIKTyRZqQo6QzbncoCy6myuTziWbgWgACwADgAdI6AGwekU2vhHCwAdVgJXSaruGu0WsmutGFKgBtp9M2Ju15tEVtFtoFYGFzvtnLz9vTPolsdqZJe6t5EYxYOj+ppRsThZTlu5TbtYE57OdXLznML4s6kAAwvlFABrfiKHwVwlV-xRiFU+sJxne5tgDmttftzlibset1e01QAcWADimG8yjAACVYIJ8Mpy6HK96FzHIHGG6vj5YWhaNzTbdMzEF12QPI9TSLQcABEIixdAmBDewwwgOcSRrRcoDPHBYFIfIfCbf9Uy3X9+QWB1OWdAAGA83X7X0pRlJJMHlJUVWQwxUNmd9z1w-Cp0hddNx5DMKLAABWCTnTEQFoP9QNEGDbjeF40IcLwgihOIltRMsdtQOdIUILk08qVLIhtlnN9MI-DSBMItcdMA0ioPI-YOxdERez7b0zKgEdFHHSdpxfazfzU7D+K0ojWRc60yIMrtvN7Bji0gC8r1ve9H2fFDKx1Wy+M0wS5OEtMxI8sQuzokUT0YqA4IQpCVJssla1CABlUFnkUOIk0mcrXOTHdpJSvM0sHaVZVY2IFWVTBVRnO50KgSLIG67xvn62KAJEttM3tIVnR83zf38yAAyDNFlvsVbCvarCNp67afzc5z9uA8SxGk4zPUm-ULLyrjXwioqupevq3uTD6gMSw7qJzEy-Ia4dRwndBBNuzU2r1CGtqhgbmVh4bBqS51aoB9TL2ga87wfJ9OO0FSHrxqBNt6nazRJvT3NeX7TNRpqIkQqyVtxjqoAANVwJIuF2kiErcncu3ZKmoGmli2IWpawpW1nJcgGWcDl7S4v2yruAkxGxB8wX0qupS0RZ9bjdNsqebKgy3Wdca+3q9LKSBsW7olp63dGIm+U9r6PPtEQTrtlH0sC4LMdC-Lwqg13ZcjhXdIO76qOopPztRzLaeyhngeZgqc5NvPufNir9JAn3-fk0JhdF1qwcej8ABVsFIfAo5kIalZGzNOR9iS6PVyBNblOb2MWpnETr8GoCHxAR7NvaW75tA3Sox1UoDwdHeUzf+4sHe9495vW0tyijJMi-AcwMsQ5xvu2cge+o987xULnHH2PYJrJ0HKnDGWM9ahz-obQBY8m4H1Jsycmf1DwLwrnTHKjNsbhgNk9ZBj80G8x3FRCBHcLrdxaqDbOW9IAADlFDOjAPaCSQoUF-ifpPMmh0qJiGRmXdKS9ZqBFXrrTO+t1qsPYZw7hZDFZe0zBJLy9tL6KWvrOYhH55EcK4fvFRL8swujqp3EsX9LK90YbfUIBjFE8InqA7gnCKYiKghdGBIV15gFsdqORbDDFKKcnw1xaBdy+08dqC6uCq65T8S7JhjijHKILqYvMFNNEWDoT-cMYd9HBPtG6MQziY7w3EjPbJUCLDiO1hxQhaE9EWEcaU4xGTW7iTdL9f6H9QhX2djff+bSynpJAZkxGM8+mWM-MHAJkYUnFPacAz6lS44ujngeBePj05JIYYEpZCiVlhPIRErM9puy9gLLU6mWV6aJKaTxI5HCVmoJMV0qqGj+mNXgiLehWdDn2KgAABRaOgXCtNynhNjtwKJWDIKxNRvUleOt9mAsWcCyAYK3CQtsKclRsKHSbPnrcqAgz0Xi0QU9HFEKrzQrOUSrMXZ3T-TJXM6xNcN66PWrSvFHSJmfLcQneiPy0ZBVgT4BZ1YsV8vpasuGytp6XMRZMOJNM8HV0pXdFpoQ5VQvGRbIVkTZJirydK+cLyjoSQZYS9ZrxLmU3ZSiyRaKnmqStUKG1hrD7thKW-GZF0KXJKxY4r1AqjVHyzHuUVsyg6cvyc0oJCjw0+ufsajhly9LePRr4i1GFQ3FNTQSguTKORGRwRqhJBD4Gal1VAMN3r3mdKjVk2i2yzV-J7gczF-8-RECUM8NQYADGckdLa0t9rIldjOl45FzFl6usabWgp1KPz9sIIOw40AR3BLHROkBTL1GugXhS91hT-QDqnNu3d7D90KvQXycmJS2WiMHPG7+5612Xs3de4do7x0Pv4Rgw6LKYlqtRrsuBMiEF2L7VeodO6AMHrWUqqplyX3YPZfEh5NaYO-zg4bDdW7-17sAyWw9U6OwioXnkr9hGnpfhXChrkskmXCO7AvF181l34dXQxj8THjQPrY1RrJmHVWpCDdom6K60IXqXIaZjInzmckudMj0C8P2WXo0C-+QnGwUc3KJtDHkongVfXOlOua9m6d7YbAz0NBokxM1Pb6e4-aVvufgrl-ie0yv08uYTRnWPnLEHuLZWG325K7UhOzAXDb2RiiF3cqmfaOi4wuiRPG17uvrRlaKpVm0uVNRmzkx0hR2zFcG4ZiXCuEWK8Z1RVSxpVbjfM-zlqsVJdKil1zAjvo+xEOBqTkGbPQZBhihLT0euOTIi585IgMOlys4OHDPntV1vWrNiNoXTE-VdO-WZ5rOsFv-hzV6LHUvseOrmfMmWZoNNy3J55WKLuEzTaV1tmyckDJk4mok378acyc8TJ+-WQMtZoitpFgdg7xa6+dyGO0+thcRifVK7KoMZ0m1SgTFh3so-m+DxbPsMeQOi3cyuuHfP5rWkwwnoPo4k-Y3uW2mPKe-Oapt-jenDYR3lqj9j6WHta1Rbx3HOr67u0a3tsrt3fvkv+yG-+AvdupcyS6M+592sJrp-ltXKmmVRPbZprH42ce1ym4j-nudBfE7QRDp9082cw4g+ldbWq8vS8brwx3zWqp7gk4ryAJ3rdnaQcPIBQuqPVRoiN-wF1uNSJ50mphpDZca4zfaLs7OaGoxqzy9PUf1dfb9WTtrF1tMvH1+tUhMfTPCtdG70b1mJW+IRxHkhJejex-Ry3xP5cq009T69-+Ge-ckTL9PdHIew947509VJoSHdT7Cz7O7anReLpy9IyXW2rVpMz9P8S9o2ch8L7Iw-Sjj8B7cVRCS1yQ-V4B-dZNISrtO-HjudTA+xRjfb1sxezf2v0-0Wy7GD2w2Hw2291AM+zv0FD3AsVoVi1fwUwbWWTGQbzcyqmkki0k0HzESyyez3ytyv0LWOTGVv1MXtBVQv2V1qyX0wNLwQI4WQNRhf1rytROVXxbC-0mWdEfw51WwsGx1HxAIoNeSwN4JK3AM4ygO8y92APy1GRYP2wizn1QK4NlXBX5V70b0FBdFNwIP-yIMe3F2ez43kyB1BV0PlWwIGzMx9hLmENhy0WunEPy31WWEnz4NYNzBkmfw63D3px0NxXsJkKa3Y2kjz1nTcNEIt3EPQOxTsINQcMhyqh9gRS82pxgOAOSO8LAONwTg0xMM7W5071CJGSLW9XSOdyqWom32yxT1gMkOtTUOzwTmEUDQLwYKLzaNTWoOz0uViKCL11OyqMNkbSKLEw8z-zFTEMqJUJqJmIMI3BiPmNmU90eWUPf3aPgP22OlKM0O520Pg1-UQ1vU8lWJwLhQy2dWIIsNIO5QX3syemIz-SQzIxuMcKti8gT1MPcKdiSJsMugQxvWQ30NuIdGOmG0s3iPMgTSWPWg+MuMhLqO-2nmkjVnN0AImzINg0X3XXBNIzvXI0iNC3Y3RwBLFW2Lw3315zeOJIuIhO+KhN+MFBnU2JQIqNDD8AAF1GAkRIB4AKAxwLBBBFA1B7d7gpwTANBxgygJAgA).

**Comment by tkf** [comment]
Maybe it's a dup of #135?

**Comment by davidanthoff** [comment]
I think #135 can't be it because you are actually not using the `@vlplot` macro at all, right?

Are you maybe using some feature of vega-lite 4? The annoying thing is that the official vega-lite documentation always shows features that haven't shipped in released versions of vega-lite yet... That would explain why things work in the online editor, but not locally...

**Comment by davidanthoff** [comment]
I'm pretty sure that is it: I tried to save the generated spec that shows fine in the online editor as a `.vegalite` file and then opened it in JupyterLab, which also ships with vega-lite 3. Display is also not correct there.

**Comment by tkf** [comment]
OK. Thanks a lot for checking it. I'm closing this since this is an upstream documentation issue.
