### ISSUE TITLE
Separating the specs to a different package

### ISSUE THREAD

**Issue by kskyten** [queryverse/VegaLite.jl#196]
Vega-Lite is awesome! Thanks for the package. It does have quite heavy dependencies though (NodeJS for example). Would it be possible to separate the specifications to a different package, so that we could have something similar to [GraphRecipes](https://github.com/JuliaPlots/GraphRecipes.jl) for Vega? Maybe it is even possible to abstract over these packages or convert from one specification to the other.

**Comment by davidanthoff** [comment]
Yeah, I've thought about a more modular structure for a while. I think something like this might be really useful:
- VegaCore.jl or VegaBase.jl: has the core spec types
- VegaLite.jl: has the vega-lite API we currently promote
- Vega.jl (that name has recently become available again): has a good API for the core vega specs (i.e. the macro we already support, and maybe a future `@vgplot` macro)
- VegaSimple.jl (or something like that): has something like the predefined visualizations API from the old Vega.jl package, see [here](http://johnmyleswhite.github.io/Vega.jl/)

If someone was up to it, we might also at some point end up with a vega backend for Plots.jl or something like that... Just in general, I'm very much in favor of exposing the underlying rendering tech via different APIs.

But, I'm not sure we would be able to get rid of the dependency on NodeJS in particular. That is needed to implement the `show` methods on the spec types, and so they kind of have to be hosted where the spec types are defined... I hope that the NodeJS dependency will become a lot more robust once we can switch to the new artifact system in Julia 1.3.

**Comment by kskyten** [comment]
Is the `show` method is for rendering the specs? Maybe it's possible to bundle the javascript into artifacts and have the front end (browser, Electron etc.) handle the rendering. Do we need to execute javascript from Julia for the rendering?

**Comment by davidanthoff** [comment]
We have `show` methods for lots of different MIME types. We actually don’t need NodeJS for the native Vega and vega-lite MIME types, but all other formats: png, pdf, svg etc. 

We need the latter for saving plots, and for showing plots in front ends that don’t natively support the Vega MIME types.

**Comment by davidanthoff** [comment]
Actually, just out of curiosity, what do you think is the issue with NodeJS.jl?

**Comment by kskyten** [comment]
I was mainly concerned about the plotting dependencies for library use in general. Not much against NodeJS.jl in particular. Javascript packages and NPMs dependency resolution are notorious for downloading massive amounts of packages, which always makes me feel uneasy.

**Comment by davidanthoff** [comment]
Completely agree, I’ve never liked that we run npm to install stuff. I think we’ll be able to skip npm entirely at some point, by using the bundled versions of vega and vega-lite for everything. There are still some issues to sort out, but I think we’re pretty close.

I think that and going back to Cairo.jl and Rsvg.jl for conversions should make the whole deployment story quite a bit better.

**Comment by davidanthoff** [comment]
Just a quick update on this: once we have a new Rsvg.jl version tagged, I can merge https://github.com/queryverse/VegaLite.jl/pull/201 and then we have a solution where we use NodeJS, but _never_ run any setup/install/npm code, everything will be xcopy. This will be true for the whole stack, i.e. _everything_ will be deployed via Julia 1.3 artifacts (NodeJS, Cairo, Rsvg and VegaLite itself). I believe at that point we should really be ok on the deployment side of things.

In terms of package reorganization, I now think it might make more sense to just have Vega, VegaLite (depends on Vega) and potentially SimpleVega (depends on Vega) at some point in the future.

My plan is to do that reorganization as soon as the artifact stuff is merged. Which depends on Rsvg moving forward :)

**Comment by tkf** [comment]
What about the (major) versions of vega/vega-lite JavaScript libraries? Would Julia's frontend libraries be coupled to their major versions? Or, after this "big split", it's going to be possible to specify JavaScript upstream major versions (maybe via `vega_jll` and `vega_lite_jll` versions)?

**Comment by tkf** [comment]
Actually, since the versions of the _spec_ is part of the MIME, I guess it doesn't matter how runtimes are updated.  But maybe it means that it's better to have some way to specify MIME version?  How about adding lightweight submodels like `v3` and `v4` s.t. `VegaLite.v3.@vlplot` produces v3 spec while `VegaLite.v4.@vlplot` spec; `VegaLite.@vlplot` can still be an alias of the latest version.  (Though I realized that my comments started to be rather tangential.)
