### ISSUE TITLE
Function-based API?

### ISSUE THREAD

**Issue by tkf** [queryverse/VegaLite.jl#197]
Macro is great at defining DSLs but I feel `@vlplot` is almost unnecessary since Julia's native syntax is pretty powerful.  If we have a macro-free API, using VegaLite.jl would be more transparent.  One benefit might be that solving #182 becomes trivial.

After writing the post below, I noticed that it was implemented before in #69.  So, my question is: can we bring it back?

---

I don't think it is difficult to use normal function call and nested named tuples for building specs.  That is to say, instead of

```julia
@vlplot(
    :bar,
    transform = [{filter = "datum.year == 2000"}],
    y = {"age:o", scale = {rangeStep = 17}},
    x = {"sum(people)", axis = {title = "population"}},
)
```

how about using

```julia
vlplot(
    :bar,
    transform = [(filter = "datum.year == 2000",)],
    y = (field = "age:o", scale = (rangeStep = 17,)),
    x = (field = "sum(people)", axis = (title = "population",)),
)
```

?  It becomes immediately obvious that you can create a helper function to construct sub-objects passed to `vlplot` function.  It can also have a `vlplot(::AbstractDict)` which creates a `VLSpec` after applying `fix_shortcuts`.

Then, `@vlplot` macro can just be a shortcut of

```julia
vlplot(@json {
    :bar,
    transform = [{filter = "datum.year == 2000"}],
    y = {"age:o", scale = {rangeStep = 17}},
    x = {"sum(people)", axis = {title = "population"}},
})
```

where (say) `@json` is a short-hand notation for creating nested `Dict`s which can be useful even without VegaLite.  Braces with positional arguments like `:bar` and `"age:o"` may be wrapped in a special type like

```julia
struct Arguments
    positional::Vector{Any}
    named::Dict{String, Any}
end
```

(I guess it's a bit weird to call it `@json` as this is not how JSON works. But I can't think of a better name ATM.)

**Comment by tkf** [comment]
Another benefit of using a function-based API is that you can define "plot recipes" for arbitrary custom types by ordinary dispatch.

**Comment by davidanthoff** [comment]
I need to think a bit more about this, don't have the bandwidth for it right now :) BUT, in general I'm probably fairly positive.

I would say, though, that we should wait with this until we have figured the package reorganization out a bit more.

**Comment by tkf** [comment]
Thanks, good to hear that you are positive about this direction.

> we should wait with this until we have figured the package reorganization

Are you talking about introducing VegaBase.jl etc. #196?  Wouldn't it be better to do it after adding function-based API, so that code boundaries are clearer?
