### ISSUE TITLE
Cannot save figure to pdf anymore

### ISSUE THREAD

**Issue by BenjaminBorn** [queryverse/VegaLite.jl#200]
Suddenly, I get the following error when saving a VegaLite plot to pdf:

> TypeError: Cannot read property 'getContext' of null
>     at resize (/Users/born/.julia/packages/VegaLite/sHyyT/deps/node_modules/vega-scenegraph/build/vega-scenegraph.js:3377:26)
>     at CanvasRenderer.prototype$6.resize (/Users/born/.julia/packages/VegaLite/sHyyT/deps/node_modules/vega-scenegraph/build/vega-scenegraph.js:3427:5)
>     at CanvasRenderer.prototype$4.initialize (/Users/born/.julia/packages/VegaLite/sHyyT/deps/node_modules/vega-scenegraph/build/vega-scenegraph.js:2989:17)
>     at CanvasRenderer.prototype$6.initialize (/Users/born/.julia/packages/VegaLite/sHyyT/deps/node_modules/vega-scenegraph/build/vega-scenegraph.js:3422:28)
>     at initializeRenderer (/Users/born/.julia/packages/VegaLite/sHyyT/deps/node_modules/vega-view/build/vega-view.js:611:8)
>     at renderHeadless (/Users/born/.julia/packages/VegaLite/sHyyT/deps/node_modules/vega-view/build/vega-view.js:716:12)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
>     at async View.renderToCanvas [as toCanvas] (/Users/born/.julia/packages/VegaLite/sHyyT/deps/node_modules/vega-view/build/vega-view.js:751:15)

It might have started after running `Pkg.update()` which let to a recompiling of NodeJS.

Minimum working example:
```julia
using VegaLite, VegaDatasets

dataset("cars") |>
@vlplot(
    :point,
    x=:Horsepower,
    y=:Miles_per_Gallon,
    color=:Origin,
    width=400,
    height=400
)  |> save(string("test.pdf"))
```

My system:
```
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
  CPU: Intel(R) Xeon(R) W-2191B CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 18
  JULIA_EDITOR = atom  -a
```

Let me know if you need more information. Thanks, Benjamin

**Comment by davidanthoff** [comment]
Ok, I can replicate that with the latest tagged version, but when I use the `master` branch version the problem goes away. Could you quickly try whether that also works for you (just do a `pkg> add VegaLite#master`), and if so, I'll tag a new release.

**Comment by BenjaminBorn** [comment]
That solves it. Thanks for the super quick reply!

**Comment by davidanthoff** [comment]
Ok, new version is tagged, just need to wait until it is registered: https://github.com/JuliaRegistries/General/pull/5637.
