### ISSUE TITLE
Reconsider use of Setfield

### ISSUE THREAD

**Issue by davidanthoff** [queryverse/VegaLite.jl#215]
@tfk, is Setfield.jl doing more stuff like https://github.com/jw3126/Setfield.jl/issues/113? I see the value it brings to the table, but on the other hand I think we should not take dependencies here that use especially clever, but at the end brittle, tricks like that one...

**Comment by tkf** [comment]
I'd say @jw3126 is generally very careful about API compliance.  The only API "violation" I can recall in Setfield.jl is [these use of generic functions in the generator body of `ConstructionBase.setproperties`](https://github.com/JuliaObjects/ConstructionBase.jl/blob/2bb8db024876adb9372f7dd86d197b101999fe4f/src/ConstructionBase.jl#L47-L49).  But these generic functions (`fieldnames`, `map`, and `issubset`) are pretty low-level in `Base` so I'm not worrying too much.  We are discussing this and tried other options https://github.com/JuliaObjects/ConstructionBase.jl/issues/21.

**Comment by davidanthoff** [comment]
Hm, ok... I am worried, I have to admit though, that it looks like Setfield is really trying to push what can be done with the compiler and seems to rely on a fair number of pretty complicated stuff (that I don't even understand from glancing at it briefly). I think it is quite normal that such things take time to bake and get stable, but for a pretty run of the mill package like VegaLite it seems not super ideal to have a dependency on something like that. Let's leave it in for now, but maybe we can keep an eye on it and I'd say that if we run into a similar issue like this crash via the `show` method we reconsider.

**Comment by tkf** [comment]
Setfield is a clever package but, compared to (say) crazy auto-diff packages, I'd say it uses pretty standard tech (the most advanced one being `@generated`).

BTW, as I mentioned in https://github.com/JuliaLang/julia/issues/29428#issuecomment-426100353, it is pretty easy to invoke this without any overload of `show(::IO, ::Type{<:MyType)`.  I think it'd be ideal to make VS code extension side more robust, at the same time removing the dangerous code from Setfield.jl.  I know at least Zygote does similar overload for `show`.

**Comment by davidanthoff** [comment]
Yeah, I'm trying to come up with a way to make the extension more robust, but it is tricky when things segfault...

**Comment by jw3126** [comment]
I am curious, why do you need to depend on `Setfield`? Does `ConstructionBase` not suffice?
