### ISSUE TITLE
Should we support 3 positional arguments at the spec level?

### ISSUE THREAD

**Issue by davidanthoff** [queryverse/VegaLite.jl#238]
At the spec level, we could make the first three positional arguments `mark`, `x` and `y`. That would enable things like `@vlplot(:point, [1,2,3], [4,5,6])` and `data |> @vlplot(:point, :colA, :colB)`.

That seems relatively safe? @tkf  and @mcmcgrath13, thoughts?

**Comment by mcmcgrath13** [comment]
Assuming that all three are optional and `x` and `y` could also still be used as keyword args for backwards compatibility (or personal preference), I see no issue with this.  It's definitely the most common usage pattern.

**Comment by davidanthoff** [comment]
Yes, this would be purely optional, i.e. the keyword versions would stay!

**Comment by tkf** [comment]
I think it is a good idea as long as it is just a sugar on top the verbose syntax.
