### ISSUE TITLE
HeadlessChromium vs Node

### ISSUE THREAD

**Issue by davidanthoff** [queryverse/VegaLite.jl#25]
I see that you are replacing the Node.js stuff with HeadlessChromium. Was there a problem with the node stuff or do you see some other benefit?

**Comment by fredo-dedup** [comment]
I don't have firm plans, just trying. The potential benefits that I see : 
- Installation is less complicated and risky (less julia packages, not a huge number of  nodes modules, only a single self sufficient zip containing the Chromium exe and libs)
- No need to keep versions of the javascript libraries of vegalite in sync  (there are the libraries that are included in the generated html pages that get rendered in the browser + the libraries called by nodejs)
- Chrome seems to be used by the VegaLite team itself as part of their tests (not sure though)

**Comment by davidanthoff** [comment]
Yes, the setup right now is not good. I think the main problem is actually the whole Cario, Rsvg stuff, that seems pretty brittle. Maybe things will become more stable once BinDeps2 is used for that, but who knows...

**Comment by davidanthoff** [comment]
I'll have another go also at making the whole NodeJS setup more robust. It just feels weird to install a full HTML browser rendering engine for this :)

Were there specific things that were brittle that you saw happening? At least in my experience, the NodeJS stuff seemed to work very reliable, the issue was more Cairo.jl and Rsvg.jl, at least in terms of getting them installed.

**Comment by davidanthoff** [comment]
A bit of an update here. I think I've gotten the NodeJS.jl setup pretty stable now, so I think using node directly should be mostly ok at this point?

Cairo.jl and friends still worry me. BUT, my understanding is that the folks that are building the new BinDeps2 story will take a crack at porting Cairo.jl over to the new BinDeps2 framework. I think that should make that part of the story much, much more stable.

So maybe the best strategy for now is to just stick with what we have on ``master``? It seems to work mostly, and I think there is a really good chance that the iffy stuff (Cairo.jl) will get much more stable if we just wait.

**Comment by davidanthoff** [comment]
I have one more update on this: I taught a class using julia this semester, and at some point also used VegaLite.jl. I had all students install VegaLite.jl and use it on their machines. Wasn't a huge number (10), but I believe it worked out of the box for everyone, which was encouraging.
