### ISSUE TITLE
is it possible to encode mark angle channel

### ISSUE THREAD

**Issue by babaq** [queryverse/VegaLite.jl#256]
I see a [Vega example](https://vega.github.io/vega/examples/wind-vectors/) showing the wedge angle could be encoded, but when I tried in Vega-Lite, it says it's not valid encode channels. I am wandering is it because Vega-Lite does not support it yet, or the Vega-Lite.jl haven't support it.

**Comment by mcmcgrath13** [comment]
It doesn't look like the exact equivalent exists in Vega-Lite.  But it does seem like you could do something similar with text (perhaps using the unicode arrow) https://vega.github.io/vega-lite/docs/text.html.

**Comment by davidanthoff** [comment]
We have much better support for `vega` on `master` now, so you could probably just code it up as a vega plot? The documentation for the vega support in VegaLite.jl is [here](https://www.queryverse.org/VegaLite.jl/dev/userguide/vega/).

I still plan to factor the vega stuff out into its own package eventually.

**Comment by babaq** [comment]
I tried to add VegaLite#master, but have package conflicts with Cairo

![image](https://user-images.githubusercontent.com/92771/72313884-bffca080-3641-11ea-9188-ae033ef4bb5a.png)

**Comment by davidanthoff** [comment]
@babaq ah, this is frustrating. I'm about to drop the dependency on Cairo to get around this problem, see https://github.com/queryverse/VegaLite.jl/pull/258 for the details.

**Comment by babaq** [comment]
I have managed to use `@vgplot` to encode mark shape, angle and size. Thanks so much @davidanthoff.

![image](https://user-images.githubusercontent.com/92771/72657179-20e3eb80-3956-11ea-9455-7e78e685868e.png)


Although it is quiet verbose, the Vega gives much more control and customization.

**Comment by davidanthoff** [comment]
Wow, that is cool! Yeah, it is verbose, but you can do a lot :)
