### ISSUE TITLE
Vega Embedded Menu Appears in Jupyter Lab

### ISSUE THREAD

**Issue by phillc73** [queryverse/VegaLite.jl#263]
I don't know if this is a bug or intended behaviour, but the Vega embed menu appears in rendered Jupyter Lab output.

Using the default example:

```julia

using Queryverse, VegaDatasets

dataset("cars") |>
@vlplot(
    :point,
    x=:Horsepower,
    y=:Miles_per_Gallon,
    color=:Origin,
    width=400,
    height=400
)
```

Displays in Jupyter Lab notebook with the Vega embedded menu:

![vega_embed_example](https://user-images.githubusercontent.com/815126/72721697-f758d900-3b7c-11ea-9fc8-d31466ee1156.png)

Ideally, this menu would not appear.

I appreciate that using [`DisplayAs.jl`](https://github.com/queryverse/VegaLite.jl/issues/187) I can remove this by forcing a static image:

```julia

using Queryverse, VegaDatasets, DisplayAs

dataset("cars") |>
@vlplot(
    :point,
    x=:Horsepower,
    y=:Miles_per_Gallon,
    color=:Origin,
    width=400,
    height=400
) |> DisplayAs.PNG

```

However, in many cases I would like to retain interactivity.

**Comment by davidanthoff** [comment]
I believe that is a choice made by the JupyterLab implementation of vega and vega-lite support, right @domoritz? I'm not aware of any option for us to control that. Essentially what we do on the Julia side of things is ship the whole spec to JupyterLab, and then it decides how to display it.

**Comment by domoritz** [comment]
Yes, it's on by default. You can disable it by passing embed options via usermeta.

**Comment by davidanthoff** [comment]
Ah, yes, I keep forgetting about that!

@phillc73 so you should be able to just add the `usermeta` information into the spec via the normal Julia constructs.

**Comment by domoritz** [comment]
By default, I’d suggest to keep the action menu active.

**Comment by davidanthoff** [comment]
Yes, so I would actually not change anything in VegaLite.jl, I think users should already be able to add a `usermeta` info piece to their spec with the existing API we have.

**Comment by phillc73** [comment]
@davidanthoff I apologise, but I could do with some assistance regarding updating the spec.

Using the information I could find [here](https://www.queryverse.org/VegaLite.jl/stable/userguide/vlspec/), [here](https://vega.github.io/vega-lite/docs/spec.html) and [here](https://github.com/vega/vega-embed), I came up with the following:

```julia

using VegaLite, VegaDatasets, Setfield

spec = vl"""
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "usermeta": {
        "embedOptions": {"actions": false}
  }
}
"""
dataset("cars") |>
@vlplot(
    :point,
    x=:Horsepower,
    y=:Miles_per_Gallon,
    color=:Origin,
    width=400,
    height=400
)

```
Whether I have the `embedOptions` and `action` parts correct, I receive the following error:

```
type VLSpec has no field usermeta

Stacktrace:
 [1] getproperty(::VegaLite.VLSpec{:plot}, ::Symbol) at ./Base.jl:20
 [2] top-level scope at In[17]:4
```

Probably missing something straight forward, but not sure where to go next. Any assistance much appreciated.

**Comment by davidanthoff** [comment]
I think it should be enough to just add the `usermeta` stuff to the normal `@vlplot` call:
```julia
dataset("cars") |>
@vlplot(
    :point,
    x=:Horsepower,
    y=:Miles_per_Gallon,
    color=:Origin,
    width=400,
    height=400,
    usermeta = {embedOptions={actions=false}}
)
```

**Comment by phillc73** [comment]
Thank you. I confirm this works. Much appreciated.

Nothing like trying to do things the hard way......

**Comment by davidanthoff** [comment]
We could think about a FAQ section in the docs where we record things like that. If you want to open a PR it would be great!
