### ISSUE TITLE
Interactivity Lost in Voila Dashboard

### ISSUE THREAD

**Issue by phillc73** [queryverse/VegaLite.jl#264]
I'm working to create a [Voila dashboard](https://github.com/voila-dashboards/voila), using the IJulia kernel and including interactive VegaLite.jl charts

Unfortunately, the interactivity which is present in a Jupyter Lab notebook is not present in the rendered Voila dashboard.

Using default example:

```julia
using Queryverse, VegaDatasets

dataset("cars") |>
@vlplot(
    :point,
    x=:Horsepower,
    y=:Miles_per_Gallon,
    color=:Origin,
    width=400,
    height=400
)
```
Results in a static image rendered with Voila, no mouseover interactivity present.

I appreciate the documentation section on [Notebook frontends](https://www.queryverse.org/VegaLite.jl/stable/gettingstarted/installation/#Notebook-frontends-1) notes that certain environments require "further steps" in order to be interactive, but I've been unable to find what those steps are!

**Comment by davidanthoff** [comment]
My best guess is that Voila doesn't support the vega and vega-lite MIME types, and in those cases it will just display a static image instead.

I don't think there is much we can do about this, the proper fix for this is that Voila should add support for those two MIME types, in the same way that JupterLab and nteract and many other Jupyter projects do.

**Comment by phillc73** [comment]
Seems that Voila uses the Jupyter Notebook renderer and there appears to be a plan to move to the Jupyter Lab renderer in the future. Some more relevant information in [this issue](https://github.com/voila-dashboards/voila/issues/166).

**Comment by davidanthoff** [comment]
Ah, yes, that would probably solve it! Great :)

**Comment by jlewis91** [comment]
Does it make sense to close this now, until voila ups support for jupyterlab?
