### ISSUE TITLE
UndefVarError when referencing variables in @vlplot in v1.0.0

### ISSUE THREAD

**Issue by Sh4pe** [queryverse/VegaLite.jl#270]
I'm using Julia **v1.3.0** and VegaLite.jl **v1.0.0** and I'm experiencing a strange bug using the `@vlplot` macro and nested definitions referencing variables. 

This is my setup code:
```julia
using DataFrames
using VegaLite
df = DataFrame(x=1:10, a=rand(10), b=(rand(10) .* 10))
min_x, max_x = -1, 12
```

This plot works fine as expected:
```julia
df |> @vlplot(
    :bar,
    encoding={
        y={field="a"},
        x={field="x"}
    }
)
```

However, when I try to set the scale of the x-axis to the values in `min_x` and `max_x`, I get this error:
```julia
df |> @vlplot(
    :bar,
    encoding={
        y={field="a"},
        x={field="x", scale={domain=[min_x, max_x]}}
    }
)

UndefVarError: min_x not defined
Stacktrace:
 [1] top-level scope at In[7]:1
```

The `@vlplot` macro seems to have problems to reference variables in such nested definitions. This is a bug, I think.

As long as the bug still exists, is there a workaround?

**Comment by Sh4pe** [comment]
Of course, defining the spec inside `@vlplot` with a dummy domain (e.g. `domain=[0,1]`) and then correcting it later with

```julia
@set recipe.encoding.x.scale.domain = [min_x, max_x]
```

works but is a bit awkward.

**Comment by Sh4pe** [comment]
The problem is gone at the current `master` as of 3c5ec84320945e155c3bad0feab4c3dea98331dc. `git bisect` shows that the problem was fixed in 484a352b3ebd600ff398628d64585ef359e90ce4.

Would it be possible to make a new release (e.g. 1.0.1) that contains 484a352b3ebd600ff398628d64585ef359e90ce4 so that users can benefit from the fix without having to fetch the current `master`?

**Comment by davidanthoff** [comment]
I'll close this for now, given that this seems fixed on `master`.

I'll just try to release a new version with everything on `master` soon, I'm too busy with other stuff right now to squeeze a point release in.

**Comment by Sh4pe** [comment]
Ok, thanks for the heads up. And thanks for the great work too! 👍
