### ISSUE TITLE
Something wrong with the new examples

### ISSUE THREAD

**Issue by oheil** [queryverse/VegaLite.jl#272]
This one
https://www.queryverse.org/VegaLite.jl/dev/examples/examples_scatter_strip_plots/#Image-based-Scatter-Plot-1
seems not to work.
The code works for me locally in the REPL and running  docs/make.jl
This is the original example:
https://vega.github.io/vega-lite/examples/scatter_image.html

Maybe something with the path composition to the images is not generic enough.

**Comment by davidanthoff** [comment]
I think we would have to put these image files into the docs/src folder and then use a relative path. The `file` protocol will certainly not work.

**Comment by oheil** [comment]
The reason is, that for the web representation the paths to the images I am calculating are not present anymore?
I will do a PR with the images in the src folder. Anything you prefer for the image path?

**Comment by davidanthoff** [comment]
A `file::` URI in the spec would be referring to that file on the end user's machine who is opening the docs in the their browser. Of course that file a) doesn't exist and b) browser security doesn't allow vega to access it :)

I think in terms of location, it would be nice if the relatives paths didn't start with `../`, other than that I don't have a strong opinion.

**Comment by oheil** [comment]
> 
> 
> A `file::` URI in the spec would be referring to that file on the end user's machine who is opening the docs in the their browser. Of course that file a) doesn't exist and b) browser security doesn't allow vega to access it :)

Indeed! :-) 

> I think in terms of location, it would be nice if the relatives paths didn't start with `../`, other than that I don't have a strong opinion.

Roger that.

**Comment by oheil** [comment]
Still not working (I expected it):
https://www.queryverse.org/VegaLite.jl/dev/examples/examples_scatter_strip_plots/#Image-based-Scatter-Plot-1

Reason:
For the own local development the paths /assets/images/ffox.png, ... are working fine, because the document root to check would be the folder docs/build, therefore docs/build/assets/images/ffox.png exists.

For the real web documentation the complete path must be
/VegaLite.jl/dev/assets/images/ffox.png

Two possible solutions for me to PR
1) relative with .. :
```
img=[
        "../../assets/images/ffox.png",
        "../../assets/images/gimp.png",
        "../../assets/images/7zip.png"
    ]
```
or 2) absolute from doc root:
```
img=[
        "/VegaLite.jl/dev/assets/images/ffox.png",
        "/VegaLite.jl/dev/assets/images/gimp.png",
        "/VegaLite.jl/dev/assets/images/7zip.png"
    ]
```
You prefer 2) ?

**Comment by davidanthoff** [comment]
Relative, I think that is way more stable if we decide to host somewhere else for example!

**Comment by oheil** [comment]
Working now :-)
