### ISSUE TITLE
DateTime issue in example Advanced Calculations

### ISSUE THREAD

**Issue by oheil** [queryverse/VegaLite.jl#279]
This issue are already mentioned here:
https://github.com/queryverse/VegaLite.jl/pull/273

The reason, why the example "Calculate Difference from Annual Average"
https://www.queryverse.org/VegaLite.jl/dev/examples/examples_advancedcalculations/#Calculate-Difference-from-Annual-Average-1
is not showing correct is the transform over dates.

This code is not working correct:
```
using VegaLite, VegaDatasets

dataset("movies") |>
@vlplot(
    transform=[
        {filter="datum.IMDB_Rating != null"},
        {timeUnit="year",field="Release_Date",as="year"},
        {
            joinaggregate= [{
                op=:mean,
                field=:IMDB_Rating,
                as="AverageYearRating"
            }],
            groupby=["year"]
        },
        {
            filter="(datum.IMDB_Rating - datum.AverageYearRating) > 2.5"
        }
    ]
) + 
@vlplot(
    mark={:bar,clip=true},
    x={"IMDB_Rating:q",axis={title="IMDB Rating"}},
    y={"Title:o"}
) +
@vlplot(
    mark=:tick,
    color={value="red"},
    x="AverageYearRating:q",
    y="Title:o"
)
```
Column "Release_Date" must be reformated to unix time format (with factor 1000 => milliseconds since 1970). Because of different formats in column "Release_Date" this is not so easily done.

The following code does reproduce the example correct. The extra code is just the DateTime reformating of column "Release_Date":

```
using VegaLite, VegaDatasets, DataFrames, Dates

df=DataFrame(dataset("movies"))
df[findall(ismissing.(df[!,:Release_Date])),:Release_Date].=""

nd=similar(df[!,:Release_Date],DateTime)
ud=similar(df[!,:Release_Date],Int)
for i in eachindex(df[!,:Release_Date])
	checked=false
	try
		nd[i]=Dates.DateTime(df[i,:Release_Date],"d-u-y")
		checked=true
	catch
	end
	if ! checked
		try
			nd[i]=Dates.DateTime(df[i,:Release_Date],"y-m-d")
			checked=true
		catch
		end
	end
	if ! checked
		try
			nd[i]=Dates.DateTime(df[i,:Release_Date],"U, y")
			checked=true
		catch
		end
	end
	if ! checked
		println(i)
		println(df[i,:Release_Date])
	end
	if Dates.year(nd[i]) < 20
		nd[i] = Dates.DateTime(Dates.year(nd[i])+2000,Dates.month(nd[i]),Dates.day(nd[i]))
	elseif Dates.year(nd[i]) > 1000
		nd[i] = Dates.DateTime(Dates.year(nd[i]),Dates.month(nd[i]),Dates.day(nd[i]))
	else
		nd[i] = Dates.DateTime(Dates.year(nd[i])+1900,Dates.month(nd[i]),Dates.day(nd[i]))
	end
	ud[i]=1000*Int(Dates.datetime2unix(nd[i]))
end
df[!,:Release_Date]=ud

df |>
@vlplot(
    transform=[
        {filter="datum.IMDB_Rating != null"},
        {timeUnit="year",field="Release_Date",as="year"},
        {
            joinaggregate= [{
                op=:mean,
                field=:IMDB_Rating,
                as="AverageYearRating"
            }],
            groupby=["year"]
        },
        {
            filter="(datum.IMDB_Rating - datum.AverageYearRating) > 2.5"
        }
    ]
) + 
@vlplot(
    mark={:bar,clip=true},
    x={"IMDB_Rating:q",axis={title="IMDB Rating"}},
    y={"Title:o"}
) +
@vlplot(
    mark=:tick,
    color={value="red"},
    x="AverageYearRating:q",
    y="Title:o"
)
```

**Comment by davidanthoff** [comment]
I don't fully understand why we need to change anything at all. If we pass the original `Release_Date` as a `String` to vega-lite, isn't it just figuring it out by itself?

**Comment by oheil** [comment]
I don't know what needs to be changed or if there is something else wrong, maybe with the example.
The straight forward implementation of the example doesn't work. Looking at the Vega Editor starting from our code and from the example at VegaLite , shows a difference in the column "Release_Date". The original from VegaLite
https://vega.github.io/vega-lite/examples/joinaggregate_mean_difference_by_year.html
has values like "782089200000" in the Data Viewer in column Release_Date. From our non working example it shows the original strings like "12-Jun-98".
Starting from this observation I tried to reformat the dates before giving them to VegaLite, and voila, the example works.
So, this issue here is just a documentation of the observed facts, because I failed to find the reason or even a solution.

**Comment by davidanthoff** [comment]
Hm, but looking at our docs, it all looks good?

The original column in the source JSON called `Release_Date` is a string, unformatted. The conversion into a unix timestamp thing is happening in vega, caused by `{timeUnit="year",field="Release_Date",as="year"}`, right? So can't we just keep it that way: we pass in the string column, and then just let vega do the parsing of the date and all of that?

**Comment by oheil** [comment]
> Hm, but looking at our docs, it all looks good?

No. This is from our docs (wrong):
![vlwrong](https://user-images.githubusercontent.com/5408557/75097326-b1db6180-55a9-11ea-8b52-3d880f72f129.png)

This is how it should be:
![vlok](https://user-images.githubusercontent.com/5408557/75097335-dfc0a600-55a9-11ea-8304-853225777a7d.png)

**Comment by oheil** [comment]
Solved with newest version.
