### ISSUE TITLE
Breaking behaviour in 2.1?

### ISSUE THREAD

**Issue by jonalm** [queryverse/VegaLite.jl#297]
The following works in 2.0.1

```julia
julia> using VegaLite, VegaDatasets
julia> dataset("stocks") |> @vlplot(:line, "date:t", :price, color=:symbol)  |> display
```
it opens my default browser automatically and shows the plot.

in 2.1.2 I get the following
```
ERROR: UndefVarError: launch_browser not defined
Stacktrace:
 [1] display(::REPL.REPLDisplay{REPL.LineEditREPL}, ::VegaLite.VLSpec) at /Users/jonalm/.julia/packages/VegaLite/minNj/src/rendering/render.jl:141
 [2] display(::Any) at ./multimedia.jl:323
 [3] |>(::VegaLite.VLSpec, ::typeof(display)) at ./operators.jl:823
 [4] top-level scope at REPL[2]:1
```

It seems like `launch_browser` was intentionally removed: https://github.com/queryverse/VegaLite.jl/commit/50e957e9c038e3f1041b9364717eeef484edc9ad#diff-d811cff51f677580fc54b9c18ea3e8a8

I'm I using the package incorrectly? How can I get the previous behavior?

**Comment by davidanthoff** [comment]
Yes, that was a bug I introduced. Fixed on master, and a new version registration is pending, should be resolved in a few minutes.
