### ISSUE TITLE
Ignoring an invalid transform: {"bandwidth":0.3,"density":"..."}.

### ISSUE THREAD

**Issue by SteffenPL** [queryverse/VegaLite.jl#306]
The example for density plots does not work on my Julia installation.

```julia 
using VegaLite, VegaDatasets

dataset("movies") |>
@vlplot(
    width=400,
    height=100,
    :area,
    transform=[
        {density="IMDB_Rating",bandwidth=0.3}
    ],
    x={"value:q", title="IMDB Rating"},
    y="density:q"
)
```

Error message:
```
WARN Ignoring an invalid transform: {"bandwidth":0.3,"density":"IMDB_Rating"}.
WARN Infinite extent for field "value": [Infinity, -Infinity]
WARN Infinite extent for field "density": [Infinity, -Infinity]
```

I don't know how to debug this situation.

Relevant output of `] status`

```
  [0ae4a718] + VegaDatasets v2.0.0
  [112f6efa]   VegaLite v1.0.0
```

**Comment by mcmcgrath13** [comment]
It looks like your VegaDatasets and VegaLite versions are both a bit outdated, can you try updating?  What Julia version are you on? I was able to run this code with:

Julia v1.4.0
VegaDatasets v2.1.0
VegaLite v2.1.3

**Comment by SteffenPL** [comment]
On plain Julia (v1.4) it does not work with VegaLite version 1.0!
With the new version it worked.

Since I am on JuliaPro (easy to install for collaborators), I am pinned to VegaLite <= 1.0.
But that's not a VegaLite problem.

Thanks for the help!
