### ISSUE TITLE
How to make animations using vegalite?

### ISSUE THREAD

**Issue by MackHarry** [queryverse/VegaLite.jl#317]
first, thanks for making the effort of writing this package, its helping me greatly!

Now, a problem I did not find a satisfactory solution for until now is how to create animations with vegalite. 
The only solution I came up with so far is creating individual frames, saving them as png files and then separately calling 
ffmpeg to bind them to an mp4 video: 

```julia
vl = @vlplot(:circle, x = [1], y = [1])

# force-feeding new data in a probably unintended way
for (x,y) in zip(2:10, collect(2:10) .^ 2)
    push!(vl.params["data"]["values"].columns[:x], x)
    push!(vl.params["data"]["values"].columns[:y], y)
    vl |> save("img_"*string(x)*".png")
end
```
While this solution is effective, it is somewhat cumbersome. 
Plots.jl's animation framework](https://docs.juliaplots.org/latest/animations/) provides facilities which, as far as I understand it, 
essentially do the above in a more concise manner, but as far as I see it does not work with vegalite. 

So how would I go about this with vegalite?

Thanks in advance.

**Comment by mcmcgrath13** [comment]
It looks like this is still an open issue on the Vega/VegaLite side of the house https://github.com/vega/vega/issues/641 . @davidanthoff do you know of a better way to do this on the Julia side?

**Comment by davidanthoff** [comment]
No, I'm not aware of anything on this, really... I think we'll just have to wait until vega adds support for this...

**Comment by MackHarry** [comment]
hm, a shame. Thanks for your support anyways.
