### ISSUE TITLE
How to wrap `@vlplot` in a function with variadic arguments?

### ISSUE THREAD

**Issue by MackHarry** [queryverse/VegaLite.jl#330]
Dear developers, 

I am trying to write a function that wraps the vegalite `@vlplot` macro in a function. 
In order to not restrict the ways in which the resulting plots can be customised, I would like to pass through 
variadic arguments of the function to the macro. However, I cannot get it to work such that the macro 
understands the arguments. 
The problem seems to be that while the macro accepts the `{x = {...}}` syntax, the core language does not. 
I tried to pass named tuples, but without consistent success: Nesting them broke the code again. 
Honestly I am somewhat at a loss here.
Any help would be greatly appreciated, since this is a somewhat important part of my current project. ..

Example of what I mean:
```julia
function wrap(data, x, y, args...) 
   data |> 
   @vlplot(x = x, y = y, args...) # this is the problem - how to pass args such that @vlplot understands them?
end
```

**Comment by MackHarry** [comment]
I read about the functional API in #227 and am quite intrigued by it for reasons stated afore. However, it does not seem to work: 

```Julia
using VegaLite
using VegaDatasets
vlplot(data = dataset("cars")) # error: convert_nt_to_dict not defined
```

**Comment by MackHarry** [comment]
I read about the functional API in #227, and would be interested what the status of this is. Is it still planned to be a feature 
that is somewhat "hidden" with the macro api having precedence? Wouldn't the functional API be more useful for use cases such as the one in my original post, or when thinking about something like Plots.jl's recipe system?

**Comment by davibarreira** [comment]
@MackHarry , have you figured it out? I'm with the same issue.

**Comment by MackHarry** [comment]
Well, first I tried to [use the functional API](https://github.com/queryverse/VegaLite.jl/blob/f9f012b84e394f9425333bc8c0491309e25af517/src/dsl_vlplot_function/dsl_vlplot_function.jl#L235), but back when I tried it, I could not get it to work because of some bug in the shortcut functions, the details of which I cannot remember and do not have the dive into right now, sry. 

In the end, I essentially reverse engineered the functional stuff, in a less elegant way then the original is: 

```julia 
"""
    nt_to_dict(item)

convert namedtuple  to orderedDict recursively and 
put any iterable tables encountered into a Vega.DataValuesNode 
such that it becomes usable for plotting. 

#### Examples

```julia
using VegaDatasets
nt = (a = 2, b = "hello", c = (df = dataset("cars")))

nt_to_dict(nt) = OrderedDict(
    a => 2, 
    b => "hello", 
    c => OrderedDict(
        df = Vega.DataValuesNode(dataset("cars"))
    )
)

````
"""
function nt_to_dict(item)
    if item isa NamedTuple
        return OrderedDict{String,Any}(
            string(k) => nt_to_dict(v) for (k, v) in pairs(item)
        )
    elseif item isa Array
        return [nt_to_dict(i) for i in item]
    elseif TableTraits.isiterabletable(item)
        it = IteratorInterfaceExtensions.getiterator(item)
        return Vega.DataValuesNode(it)
    else
        return item
    end
end

"""
    vegalite(; kwargs...)

Create a plot from a vegalite specification as keyword arguments naming namedtuples. 
If one of the named tuples contains only one element, do not forget to add a trailing 
comma, or it will be interpreted as a variable in parantheses, and fail to build.
Also, mind that this function only(!) accepts variadic keyword arguments, 
so failing to include a starting semicolon will produce nasty error messages.
#Examples

```julia
using VegaDatasets 
using UtopiaViz

v = vegalite(;
    data = (values = dataset("cars"),),
    mark = (type = :circle,),
    encoding = (
        x = (field = :Cylinders,), 
        y = (field = :MilesPerGallon,),
        color = (field = :Origin,),
    ),
)
```

It can also be used without specifying data immediatelly, such that 
repeated generation of a specification can be avoided.

```julia
using VegaDatasets 
using UtopiaViz

# build without data 
v = vegalite(;
    mark = (type = :circle,),
    encoding = (
        x = (field = :Cylinders,), 
        y = (field = :MilesPerGallon,),
        color = (field = :Origin,),
    ),
)

# pipe data into specification to generate a plot
data("cars") |> v
```
"""
function vegalite(; kwargs...)
    VegaLite.VLSpec(nt_to_dict(namedtuple(collect(kwargs))))
end
```

The `nt_to_dict` in essence is a. copy of the `vegalite.nt_to_dict`, without all the shortcuts that are implemented therein. The `vegalite` function then gets a number of namedtuples as keyword arguments and passes them via `nt_to_dict` to a `VLSpec` object that then uses the `vegalite` functionality again to save and manipulate plots. As a consequence of "custom" `nt_to_dict` function, you are stuck with the normal vegalite syntax as described [in the original vegalite tutorial](https://vega.github.io/vega-lite/tutorials/getting_started.html), mapping the `{x:y, z:r}` syntax to namedtuples by `{ --> (, }-->) and : --> =`, with a comma at the end for namedtuples with only one variable: `{x:z} --> (x=z,)`.  I posted the documentation as well for examples. As said, not the best solution, but I was under some time-pressure at the time and went with a quick-and-dirty solution instead of a fixing PR here. 

Hope this still helps, sry for the long time it took me to answer.

**Comment by MackHarry** [comment]
This then enabled me to write wrapping functions as usual. But I would try the supplied functional api instead of the custom one, unless you prefer the default vegalite syntax or so, maybe that does the trick for you ...

**Comment by davidanthoff** [comment]
Sorry that I didn't respond for such a long time, was a busy year :)

The functional API really consists of `vlfrag` and `vlplot` (for the top level). Both functions are exported, so we consider them part of the official API. @MackHarry if you remember what blocked you from using them, let me know, we do want that to work for situations like yours!

Having said that, I'm going to close this issue, because the "official" answer is to use the functional API :) New issues with specific bugs around that API would be very welcome.
