### ISSUE TITLE
VegaLite plots not displaying in VS Code

### ISSUE THREAD

**Issue by matthijscox** [queryverse/VegaLite.jl#339]
First of all, I love using VegaLite.jl. It works perfectly in Jupyter!

However, for some reason it does not render any plot in my VS Code environment. Even the simplest possible @vlplot command will open an empty plot pane:
```
using VegaLite, DataFrames
df = DataFrame(x=1:5, y=1:5)
@vlplot(mark=:line, data=df, x=:x, y=:y)
```
![image](https://user-images.githubusercontent.com/17245881/97286050-4f76e700-1843-11eb-8c67-4cfbec801eda.png)

The documentation mentions VegaLite.jl should work out of the box with VS Code, so I'm at a loss. 

I'm using: 
VegaLite v1.0.0
VS Code version 1.50 (September 2020 release)
Julia 1.5.1

Plots.jl does work in VS Code and renders a figure in the plot pane.

Please let me know if I should provide more information.

**Comment by danielw2904** [comment]
Your vegalite version seems quite old. Could you try updating it?

**Comment by matthijscox** [comment]
Thanks, that fixed it! My apologies for not realizing such an easy fix.

**Comment by danielw2904** [comment]
This happens to me all the time. I add VegaLite to a project and it adds an old version. I have never really tracked that down but I assume it's another package holding it back

**Comment by daxmahoney** [comment]
I too fixed by updating when I had this issue thank you. (pkg > update)
