### ISSUE TITLE
problem with VegaLite in jupyter notebook with julia kernel

### ISSUE THREAD

**Issue by meghamankal** [queryverse/VegaLite.jl#340]
![piechart](https://user-images.githubusercontent.com/65075546/98555425-ee7df300-22c7-11eb-99ef-fdb27ff643ff.PNG)
I have added the package but still, it is showing the error

**Comment by davidanthoff** [comment]
`piechart` is not something that exists in VegaLite, make sure to read the docs for VegaLite to get a sense on how to use it :)
