### ISSUE TITLE
I cannot reproduce this example plot from Vega-lite

### ISSUE THREAD

**Issue by kavir1698** [queryverse/VegaLite.jl#347]
I am trying to set color values from a field, replicating [this example](https://vega.github.io/vega-lite/docs/scale.html#example-setting-color-range-based-on-a-field). However, I get no plot. Here is my code:

```julia
using VegaLite
using DataFrames

df = DataFrame(Dict(
  :y => ["X", "Y", "Z"],
  :l => ["A", "B", "C"],
  :c => ["red", "green", "blue"]
))

df |> @vlplot(
  mark = :circle,
  y = "y:n",
  color = {
    field = "l:n",
    scale = {range = {field = :c}}
  }
)
```

I have tested it with VegaLite v2.3.0 on Windows and Linux. Is this a bug?

**Comment by Nosferican** [comment]
Seems the scale range expects a number, but you are passing text.

**Comment by kavir1698** [comment]
Text works in the original vega-lite example.

**Comment by mcmcgrath13** [comment]
what if you use the literal `"c"` instead of `:c`?

**Comment by kavir1698** [comment]
Doesn't help.

**Comment by mcmcgrath13** [comment]
It looks like this feature was added in vega-lite v4.14 and VegaLite.jl currently uses v4.13, so this will become supported whenever that update is made. https://github.com/vega/vega-lite/releases/tag/v4.14.0

**Comment by kavir1698** [comment]
Right! Thanks for the feedback.
