### ISSUE TITLE
Update vega-lite version

### ISSUE THREAD

**Issue by lassepe** [queryverse/VegaLite.jl#357]
If I understand it correctly, the latest release and current master (f9f012b84e394f9425333bc8c0491309e25af517) of VegaLite.jl use  vega-lite 4.13.0 via VegaLiteBuilder 2.5.1. There have been a few bug fixes since then in the upstream vega-lite library. Therefore, I was wondering whether it could be updated here.

Personally, I came across a bug with the legend opacity which was fixed in vega-lite 4.14.0. If vega-lite sticks to SemVer it may be worth updating directly to 4.17.0.

**Comment by jlewis91** [comment]
This sounds like a manageable change and one I'd be happy to contribute. :)

**Comment by lassepe** [comment]
It seems like most of the work would (hopefully) not have to happen here but in [VegaLiteBuilder](https://github.com/queryverse/VegaLiteBuilder) before updating the [Artifacts.toml](https://github.com/queryverse/VegaLite.jl/blob/master/Artifacts.toml).

**Comment by jlewis91** [comment]
See here for the PR: https://github.com/queryverse/VegaLiteBuilder/pull/6

**Comment by jlewis91** [comment]
@davidanthoff Just wanted to follow up on this, looks like vegalite 5.0 was just released with a few interesting new features. I'd be happy to attempt the changes necessary to make this upgrade, please let me know if you'd entertain a PR. :)
