### ISSUE TITLE
Remove commented out tests

### ISSUE THREAD

**Issue by jlewis91** [queryverse/VegaLite.jl#365]
There seems to be a fair number of commented out tests which, afaict, could be all eliminated; they either refer to functionality which is based in the Vega.jl package or seem to reflect a long deprecated / eliminated API. The only exception to this is the following test in test_io.jl:

```julia
save(joinpath(folder,"test2.eps"), p)
@test isfile(joinpath(folder,"test2.eps"))
```

@davidanthoff I believe that this test could be re-enabled if ImageMagick.jl were added to the dependencies as an extra; let me know if you would like a PR on this matter

**Comment by davidanthoff** [comment]
The reason we had the EPS tests in there is that in a previous version we were using Cario.jl and Rsvg.jl, and they natively supported eps files, whereas our current story doesn't. I'd say we can just remove those tests entirely.
