### ISSUE TITLE
Is VegaLite.jl abandoned/unmaintained?

### ISSUE THREAD

**Issue by brucala** [queryverse/VegaLite.jl#413]
The last commit to this repo was back in June, and all recent PRs seem to be stalled. So I'm wondering, is VegaLite.jl abandoned or unmaintained?

I think it's awesome to have an option to create Vega-Lite plots in Julia, and I find that VegaLite.jl does a pretty good job at it. I truly appreciate all the effort by all VegaLite.jl contributors! However, I would be sadden to learn that there will be no further developments to make this package even better. I hope it's just a temporary pause.

**Comment by ericqu** [comment]
I hope it is not abandoned. However, I feel that the limited time is partly because the library is meant as a wrapper to the main vega-lite library.
Though, I guess it is more for the primary maintainer to answer @davidanthoff.

**Comment by davidanthoff** [comment]
Definitely not abandoned, I was just _very_ busy the last six months with another project (where we used this package extensively). It will probably be a little longer before I get around to process the pending PRs here (there are a lot repos at the moment that are waiting for my attention). But on the plus side, at least for the scenario where I used the package, it mostly "just works" :)

**Comment by jeremiahpslewis** [comment]
@davidanthoff Have you considered / would you entertain taking on a co-maintainer for this project to reduce your workload? To be clear, I am not personally qualified for / intending to insinuate myself into the role, rather I think this type of transition towards broadening maintainer / contribution bases is something many excellent Julia packages would benefit from and I was wondering whether you have thought about this in the context of queryverse.
