### ISSUE TITLE
Support for VegaLite 5

### ISSUE THREAD

**Issue by rben01** [queryverse/VegaLite.jl#420]
Because of a personal need for VegaLite 5, I've gone through the effort of updating the VegaLite.jl and VegaLiteBuilder packages to VLv5, which also required updating NodeJS.jl and its builder package to a version of node supporting the latest ECMAScript syntax.

My forks:

- https://github.com/rben01/VegaLite.jl/tree/update-vegalite-v5
 
- https://github.com/rben01/VegaLiteBuilder/tree/update-vegalite-v5 

- https://github.com/rben01/NodeJS.jl/tree/update-node-v17

- https://github.com/rben01/NodeJSBuilder/tree/update-node-v17

An environment with these packages (created with e.g., `pkg> add https://github.com/rben01/VegaLite.jl#update-vegalite-v5`) works fine for me. The only issue I'm facing is that when using VSCode's plot pane, plots are rendered with VegaLite v4 instead of v5 -- I think this is a VSCode issue, though. Saving to a file uses VegaLite v5.

I was wondering if it would be possible to have these integrated back into their respective queryverse repos. The builder packages would need to be be rewritten to generate artifacts pointing to the queryverse version of resources instead of the rben01 version, and probably some docs would need to be updated, some version numbers checked, etc, but otherwise I'd love to see these forks make it back upstream.

**Comment by asbisen** [comment]
Would love to see VegaLite updated, wondering if there is more work required than what @rben01 has done already?

**Comment by davidanthoff** [comment]
So the main reason why I haven't updated already is that I'm worried what will happen with JupyterLab support... JupyterLab ships with vega-lite MIME support out of the box, _but_ it is really slow to update the version of vega-lite it ships. So if we move now to vega-lite 5, with a new MIME type, we might completely lose the JupyterLab vega-lite support....

So I think one thing we need to do is understand whether that is the case or not, i.e. what version of vega-lite is currently shipping in JupyterLab. But I'm also coming to a point where we might just have to live with this...

We can easily update the VS Code extension to the latest vega-lite, once we make the switch here.

**Comment by asbisen** [comment]
Just noticed that altair has bumped the supported vega-lite version to 5.x in their [master branch](https://github.com/altair-viz/altair/blob/8a3c6b9dd0a3eb700adc0fbbc89a259317825a4f/doc/releases/changes.rst)
