### ISSUE TITLE
Improve Juno integration

### ISSUE THREAD

**Issue by davidanthoff** [queryverse/VegaLite.jl#90]
Main thing would be to get the interactive stuff working.

**Comment by pfitzseb** [comment]
For reference: https://github.com/JunoLab/Juno.jl/issues/125#issuecomment-378622805

Juno's API for things like this will (hopefully) change drastically soon since I'm hoping to get rid of the Blink.jl dependency... I can take another look at this then.

**Comment by davidanthoff** [comment]
Would be great if we could take another look at this, given for example https://discourse.julialang.org/t/vega-lite-width-and-height-in-heatmap-in-juno-sometimes-doesnt-work/33262/4.

@pfitzseb, I haven't followed the Juno plot story, I assume it is now using MIME types and the normal display stuff? In VS Code and ElectronDisplay.jl we just support the vega and vega-lite MIME types out of the box (essentially emulating JupyterLab and nteract). So we ship the javascript client libraries that are need to display these MIME types as part of these clients, and then get interactivity that way. What would our current options for Juno be? Similar story, or something else?

**Comment by pfitzseb** [comment]
So in theory
```
function Base.show(io::IO, m::MIME"application/prs.juno.plotpane+html", v::VegaLite.VGSpec)
    VegaLite.writehtml_full(io, v)
end

function Base.show(io::IO, m::MIME"application/prs.juno.plotpane+html", v::VegaLite.VLSpec)
    VegaLite.writehtml_full(io, v)
end
```
should work, except for the fact that `writehtml_full` doesn't have a method for `VLSpec`/`VGSpec`.

**Comment by davidanthoff** [comment]
That is perfect! I know how to sort out the details inside those functions.
