### ISSUE TITLE
Move JSON Schema parser/stuff into own package

### ISSUE THREAD

**Issue by davidanthoff** [queryverse/VegaLite.jl#93]
I'm not really sure this makes sense, but if the JSON schema stuff is generic enough that it is not vega-lite specific, it might make use to move it into a JSONSchema.jl package, so that other packages can also use it?

**Comment by fredo-dedup** [comment]
I have been thinking about this too. I'll give it a try.

**Comment by fredo-dedup** [comment]
I finished the JSONSchema package handling the JSON validation function. It is in the process of being registered.
I'd like to start the adaptation of VegaLite but I am not sure where to start. Ideally this should be on a branch compliant with julia 0.7 and 1.0. 
Should I start a new branch off the current `master` or should I wait ? What is your advice ?

**Comment by davidanthoff** [comment]
Alright, I think we could do this now. ``master`` is julia 0.7/1.0 only, we have tagged a release, so now might be a good time to sort this out?

**Comment by fredo-dedup** [comment]
Thanks David. I'll start as soon as I can.
